# Generated by Django 5.2.6 on 2025-09-29 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('fuerza', 'Fuerza'), ('cardio', 'Cardio'), ('flexibilidad', 'Flexibilidad')], default='fuerza', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Ejercicios',
            },
        ),
        migrations.CreateModel(
            name='RutinaEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('completado', models.BooleanField(default=False)),
                ('meta_cantidad', models.IntegerField(help_text='Cantidad objetivo (repeticiones, minutos, etc.)')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_rutina', to='bienestar.ejercicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas_ejercicio', to='bienestar.usuario')),
            ],
            options={
                'verbose_name_plural': 'Rutinas de Ejercicio',
                'unique_together': {('usuario', 'ejercicio', 'fecha_registro')},
            },
        ),
    ]
