# Generated by Django 5.2.6 on 2025-10-04 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar', '0002_ejercicio_rutinaejercicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Hábitos',
            },
        ),
        migrations.CreateModel(
            name='ProgresoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('completado', models.BooleanField(default=False)),
                ('habito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='bienestar.habito')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='bienestar.usuario')),
            ],
            options={
                'verbose_name_plural': 'Progresos Diarios',
                'unique_together': {('usuario', 'habito', 'fecha')},
            },
        ),
    ]
