# Generated by Django 5.2.6 on 2025-10-04 02:02

from django.db import migrations

def crear_habitos_iniciales(apps, schema_editor):
    Habito = apps.get_model("bienestar", "Habito")
    habitos = [
        "Ejercicio",
        "Hidratación",
        "Horas de sueño",
        "Alimentación saludable",
        "Meditación"
    ]
    for nombre in habitos:
        Habito.objects.get_or_create(nombre=nombre)

def eliminar_habitos_iniciales(apps, schema_editor):
    Habito = apps.get_model("bienestar", "Habito")
    Habito.objects.filter(
        nombre__in=[
            "Ejercicio",
            "Hidratación",
            "Horas de sueño",
            "Alimentación saludable",
            "Meditación"
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar', '0003_habito_progresodiario'),
    ]

    operations = [
        migrations.RunPython(crear_habitos_iniciales, eliminar_habitos_iniciales),
    ]
