# Generated by Django 5.2.6 on 2025-10-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar', '0005_alter_progresodiario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
