# Generated by Django 5.2.6 on 2025-10-08 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar', '0006_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AlterModelOptions(
            name='perfilsalud',
            options={'verbose_name_plural': 'Perfiles de Salud'},
        ),
        migrations.AlterModelOptions(
            name='recomendacion',
            options={'verbose_name_plural': 'Recomendaciones'},
        ),
        migrations.AlterModelOptions(
            name='recurso',
            options={'verbose_name_plural': 'Recursos'},
        ),
        migrations.RemoveField(
            model_name='perfilsalud',
            name='imc',
        ),
        migrations.AlterField(
            model_name='perfilsalud',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
