# Generated by Django 5.2.6 on 2025-10-08 04:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar', '0007_alter_notificacion_options_alter_perfilsalud_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rutinaejercicio',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Registro de Rutina', 'verbose_name_plural': 'Registros de Rutinas'},
        ),
        migrations.AlterUniqueTogether(
            name='rutinaejercicio',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='rutinaejercicio',
            name='fecha_registro',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rutinaejercicio',
            name='meta_cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
