# Generated by Django 5.2.6 on 2025-10-15 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar', '0008_alter_rutinaejercicio_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresodiario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='bienestar.usuario'),
        ),
    ]
