# Generated by Django 5.2.6 on 2025-10-18 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar', '0008_alter_rutinaejercicio_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={},
        ),
    ]
