# Generated by Django 5.2.6 on 2025-10-16 01:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar', '0009_alter_progresodiario_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgresoChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('completado', models.BooleanField(default=False)),
                ('progresos', models.ManyToManyField(related_name='checklists', to='bienestar.progresodiario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='bienestar.usuario')),
            ],
            options={
                'verbose_name_plural': 'Progresos Checklist',
                'ordering': ['-fecha'],
                'unique_together': {('usuario', 'fecha')},
            },
        ),
    ]
