# Generated by Django 5.2.6 on 2025-10-18 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar', '0009_alter_notificacion_options'),
        ('bienestar', '0010_progresochecklist'),
    ]

    operations = [
    ]
