# Generated by Django 5.2.6 on 2025-10-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar', '0011_merge_20251018_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progresochecklist',
            options={'verbose_name_plural': 'Progresos Diarios'},
        ),
        migrations.AlterUniqueTogether(
            name='progresochecklist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='progresochecklist',
            name='habito',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='progresochecklist',
            unique_together={('usuario', 'habito', 'fecha')},
        ),
    ]
