# Generated by Django 5.2.6 on 2025-10-20 01:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar', '0011_merge_20251018_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AlterField(
            model_name='progresodiario',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
