# Generated by Django 5.2.6 on 2025-10-20 02:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar', '0012_alter_notificacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresodiario',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='rutinaejercicio',
            name='fecha_registro',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterUniqueTogether(
            name='rutinaejercicio',
            unique_together={('usuario', 'ejercicio', 'fecha_registro')},
        ),
    ]
