# Generated by Django 5.2.6 on 2025-10-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar', '0013_alter_progresodiario_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilsalud',
            name='mostrar_modal_imc',
            field=models.BooleanField(default=True, help_text='Indica si el modal de recomendación inicial debe ser mostrado al usuario.'),
        ),
    ]
