# Generated by Django 5.2.6 on 2025-10-20 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar', '0012_alter_progresochecklist_options_and_more'),
        ('bienestar', '0014_perfilsalud_mostrar_modal_imc_and_more'),
    ]

    operations = [
    ]
