# Generated by Django 5.2.6 on 2025-10-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar', '0015_merge_20251020_2037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progresochecklist',
            options={'ordering': ['-fecha'], 'verbose_name_plural': 'Progresos Checklist'},
        ),
        migrations.AlterUniqueTogether(
            name='progresochecklist',
            unique_together={('usuario', 'fecha')},
        ),
        migrations.AddField(
            model_name='perfilsalud',
            name='recomendacion_enfoque',
            field=models.CharField(blank=True, choices=[('FUERZA_CARDIO', 'Fuerza y Cardio'), ('FLEXIBILIDAD_MANTENIMIENTO', 'Flexibilidad y Mantenimiento')], help_text='Recomendación de enfoque de ejercicio basada en el IMC', max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='progresochecklist',
            name='habito',
        ),
    ]
