# Generated by Django 5.2.6 on 2025-10-23 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar', '0016_alter_progresochecklist_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='mail',
            new_name='email',
        ),
    ]
