# Generated by Django 5.2.6 on 2026-09-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar', '0017_rename_mail_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil_id',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
